#!/bin/bash

EXTENSIONS="
@jupyter-widgets/jupyterlab-manager
ipydagred3
ipyregulartable
@finos/perspective-jupyterlab
"

jupyter labextension install $EXTENSIONS --no-build
jupyter lab build --dev-build=False --minimize=False

jupyter serverextension enable --py jupyterlab
